### ISSUE TITLE
Issue #2 - Maternal Parent Cell NOT Highlighted.

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/germ_summary#2]
![gs](https://user-images.githubusercontent.com/15472253/32068070-71b40ef4-ba42-11e7-8970-d72937b2620b.gif)

The maternal parent header row is not highlighted in the same way as the paternal parent column when mouse pointer is on siblings cell.

This is cause by theme_table setting that creates a sticky header where table head markups get duplicated (id, class etc. attributes) causing multiple elements of the same id in the DOM and scripts could not ascertain element/cell to highlight.

**Comment by laceysanderson** [comment]
This issue was fixed in the above mentioned pull request.
