### ISSUE TITLE
Not summarizing F-stage

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/germ_summary#6]
Currently the F-stage is not being indicated in the Summary (http://knowpulse.usask.ca/portal/germplasm/list/Lens/4/4)
![screen shot 2018-04-27 at 3 54 59 pm](https://user-images.githubusercontent.com/1566301/39386771-6f5601ae-4a33-11e8-8861-4fb67355cf00.png)
Despite confirmation that the properties have been entered:
![screen shot 2018-04-27 at 3 56 15 pm](https://user-images.githubusercontent.com/1566301/39386802-9526a140-4a33-11e8-9bd1-7e2aec024428.png)

**Comment by reynoldtan** [comment]
Issue cause by cvterm stock_properties not found in the chado.
To Fix:
Change stock_properties to stock_property.

**Comment by laceysanderson** [comment]
Fixed by PR :-)

**Comment by laceysanderson** [comment]
Updated on KnowPulse :-)
