### ISSUE TITLE
Create Field for the germplasm summary

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/germ_summary#9]
We would like to create a Tripal 3 Field that displays the germplasm summary on an organism page.

Specification:
 - Should extend ChadoField, ChadoFieldWidget and ChadoFieldFormatter
 - Use the ChadoField example from the tripal_example module. This will magically retrieve the organism_id based on the entity. You can then use that to determine which genus chart to display
- Warning: the cvterm you choose must already exist or your field won't show in the drop-down,etc
- The ChadoFieldFormatter is where you add the code to display the chart.
- clicking on the cell is expected to jump out to the requested page just as it does now (no need to embed the stock listing)

Resources:
 - Developers Guide: http://tripal.info/tutorials/v3.x/developers_handbook/custom-field
 - Tutorial for Custom Tripal Fields here: https://github.com/tripal/tripal_example/blob/7.x-3.x/trpexp_fields/tutorial/trpexp_fields_custom_field.md
 - Tripal Example here: https://github.com/tripal/tripal_example/tree/7.x-3.x/trpexp_fields
 - More Examples: https://github.com/tripal/trpfancy_fields/

**Comment by reynoldtan** [comment]
![Screen Shot 2019-03-18 at 1 32 48 PM (2)](https://user-images.githubusercontent.com/15472253/54558114-7fc98480-4982-11e9-805b-aa5294947587.png)
